maps/aa_dima2.bsp
maps/aa_dima2.res
cs_cbble.wad
cs_dust.wad
de_storm.wad
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
maps/aa_dima2.txt
torntextures.wad